version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '6669:6669'
    environment:
      MONGOUSER: ${MONGOUSER}
      MONGOPASSWORD: ${MONGOPASSWORD}
      PORT: ${PORT}
    volumes:
      - .:/src
      - /node_modules
    command: npm run start:dev
